/*
 * JWebImgApplication.java
 *
 * Created on 30. September 2002, 15:55

 */

package net.flockhost.jwebimg;

import net.flockhost.jwebimg.config.JWebImgConfig;
import net.flockhost.jwebimg.engine.JWebImgThread;
import net.flockhost.jwebimg.ui.LogFrame;

import javax.swing.*;

/**
 *
 */
public class JWebImgApplication extends javax.swing.JFrame {

  private LogFrame log = new LogFrame();
  private JFileChooser fileChooser = new JFileChooser();

  /**
   * Creates new form JWebImgApplication
   */
  public JWebImgApplication() {
    initComponents();
    this.setSize(550, 300);
    this.setResizable(false);
    log.setSize(500, 250);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    jPanel1 = new javax.swing.JPanel();
    lblImageDir = new javax.swing.JLabel();
    tfImageDir = new javax.swing.JTextField();
    btnImageDir = new javax.swing.JButton();
    btnGenerateThumbnails = new javax.swing.JButton();
    lblMaxWidth = new javax.swing.JLabel();
    tfMaxWidth = new javax.swing.JTextField();
    tfMaxHeight = new javax.swing.JTextField();
    lblMaxHeight = new javax.swing.JLabel();
    lblTemplateFile = new javax.swing.JLabel();
    tfTemplateFile = new javax.swing.JTextField();
    btnTemplateFile = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jTextArea1 = new javax.swing.JTextArea();
    menuBar = new javax.swing.JMenuBar();
    fileMenu = new javax.swing.JMenu();
    exitMenuItem = new javax.swing.JMenuItem();

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    jPanel1.setLayout(null);

    lblImageDir.setText("Image Directory");
    jPanel1.add(lblImageDir);
    lblImageDir.setBounds(10, 10, 110, 20);

    tfImageDir.setEditable(false);
    tfImageDir.setText(".");
    jPanel1.add(tfImageDir);
    tfImageDir.setBounds(120, 10, 250, 20);

    btnImageDir.setText("open...");
    btnImageDir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnImageDirActionPerformed(evt);
      }
    });

    jPanel1.add(btnImageDir);
    btnImageDir.setBounds(380, 10, 90, 20);

    btnGenerateThumbnails.setText("generate");
    btnGenerateThumbnails.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGenerateThumbnailsActionPerformed(evt);
      }
    });

    jPanel1.add(btnGenerateThumbnails);
    btnGenerateThumbnails.setBounds(380, 100, 90, 30);

    lblMaxWidth.setText("max width");
    jPanel1.add(lblMaxWidth);
    lblMaxWidth.setBounds(40, 70, 80, 20);

    tfMaxWidth.setText("100");

    jPanel1.add(tfMaxWidth);
    tfMaxWidth.setBounds(120, 70, 50, 20);

    tfMaxHeight.setText("100");
    jPanel1.add(tfMaxHeight);
    tfMaxHeight.setBounds(280, 70, 50, 20);

    lblMaxHeight.setText("max height");
    jPanel1.add(lblMaxHeight);
    lblMaxHeight.setBounds(200, 70, 80, 20);

    lblTemplateFile.setText("Template File");
    jPanel1.add(lblTemplateFile);
    lblTemplateFile.setBounds(10, 40, 110, 20);

    tfTemplateFile.setEditable(false);
    jPanel1.add(tfTemplateFile);
    tfTemplateFile.setBounds(120, 40, 250, 20);

    btnTemplateFile.setText("open...");
    btnTemplateFile.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnTemplateFileActionPerformed(evt);
      }
    });

    jPanel1.add(btnTemplateFile);
    btnTemplateFile.setBounds(380, 40, 90, 20);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    jPanel2.setLayout(new java.awt.BorderLayout());

    jPanel2.setBorder(new javax.swing.border.TitledBorder("Help"));
    jTextArea1.setBackground((java.awt.Color) javax.swing.UIManager.getDefaults().get("Button.background"));
    jTextArea1.setEditable(false);
    jTextArea1.setText("  Thumbnails will be generated into the image directory.\n  The Thumbnails will have the text \"_jwebimg_\" as a prefix.");
    jPanel2.add(jTextArea1, java.awt.BorderLayout.CENTER);

    getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

    exitMenuItem.setText("Exit");
    exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitMenuItemActionPerformed(evt);
      }
    });

    fileMenu.add(exitMenuItem);

    menuBar.add(fileMenu);

    setJMenuBar(menuBar);

    pack();
  }//GEN-END:initComponents

  private void btnGenerateThumbnailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_generateThumbnailsActionPerformed

    //open log window
    log.show();

    //set configuration and start image-processing-thread
    if (setConfiguration()) {
      new Thread(new JWebImgThread(log)).start();
    }
  }//GEN-LAST:event_b_generateThumbnailsActionPerformed

  private boolean setConfiguration() {
    JWebImgConfig config = JWebImgConfig.getInstance();
    config.setInputPath(tfImageDir.getText());
    config.setTemplateFile(tfTemplateFile.getText());
    try {
      config.setMaxWidth(Integer.parseInt(tfMaxWidth.getText()));
    } catch (NumberFormatException nfe) {
      logError("max width not numeric");
      return false;
    }
    try {
      config.setMaxHeight(Integer.parseInt(tfMaxHeight.getText()));
    } catch (NumberFormatException nfe) {
      logError("max height not numeric");
      return false;
    }
    return true;
  }

  private void logError(String message) {
    log.append("Error: " + message + "\n");
  }

  private void btnTemplateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_templateFileActionPerformed
    fileChooser = new JFileChooser(".");
    fileChooser.setFileSelectionMode(fileChooser.FILES_AND_DIRECTORIES);
    //fileChooser.setFileFilter( new TemplateFileFilter() );
    fileChooser.showOpenDialog(this);
    if (fileChooser.getSelectedFile() != null) {
      tfTemplateFile.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }
  }//GEN-LAST:event_b_templateFileActionPerformed

  private void btnImageDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_imageDirActionPerformed
    fileChooser = new JFileChooser();
    fileChooser.setFileSelectionMode(fileChooser.DIRECTORIES_ONLY);
    fileChooser.showOpenDialog(this);
    if (fileChooser.getSelectedFile() != null) {
      tfImageDir.setText(fileChooser.getSelectedFile().getAbsolutePath());
    }
  }//GEN-LAST:event_b_imageDirActionPerformed

  private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
    System.exit(0);
  }//GEN-LAST:event_exitMenuItemActionPerformed

  /**
   * Exit the Application
   */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit(0);
  }//GEN-LAST:event_exitForm

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new JWebImgApplication().show();
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField tfImageDir;
  private javax.swing.JButton btnImageDir;
  private javax.swing.JLabel lblImageDir;
  private javax.swing.JTextField tfMaxWidth;
  private javax.swing.JMenu fileMenu;
  private javax.swing.JMenuItem exitMenuItem;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JLabel lblMaxHeight;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JLabel lblTemplateFile;
  private javax.swing.JButton btnGenerateThumbnails;
  private javax.swing.JButton btnTemplateFile;
  private javax.swing.JTextField tfTemplateFile;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblMaxWidth;
  private javax.swing.JTextField tfMaxHeight;
  // End of variables declaration//GEN-END:variables

}
