package net.flockhost.jwebimg.ui;

import net.flockhost.jwebimg.engine.LogMessageReceiver;

/**
 * A Swing frame that can display log messages.
 */
public class LogFrame extends javax.swing.JFrame implements LogMessageReceiver {

  /**
   * Creates new form LogFrame.
   */
  public LogFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents() {//GEN-BEGIN:initComponents
    spLog = new javax.swing.JScrollPane();
    taLog = new javax.swing.JTextArea();

    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        exitForm(evt);
      }
    });

    taLog.setEditable(false);
    taLog.setText("Log:\n");
    spLog.setViewportView(taLog);

    getContentPane().add(spLog, java.awt.BorderLayout.CENTER);

    pack();
  }//GEN-END:initComponents

  /**
   * Exit the Application
   */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    this.hide();
  }//GEN-LAST:event_exitForm

  public void append(String text) {
    new Thread(new LogAppenderThread(taLog, text)).run();
  }

  public void setText(String text) {
    taLog.setText(text);
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea taLog;
  private javax.swing.JScrollPane spLog;
  // End of variables declaration//GEN-END:variables

}
